#!/usr/bin/env bash

php LEFthird/propel/buildproperties.php

if [ $# = 1 ] ; then
    "LEFthird/phing/bin/phing" -f "LEFthird/propel/generator/build.xml" -Dusing.propel-gen=true -Dproject.dir=$saveddir $*
else
    "LEFthird/phing/bin/phing" -f "LEFthird/propel/generator/build.xml" -Dusing.propel-gen=true -Dproject.dir=$*
fi

php LEFthird/propel/deleteproperties.php